# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/development.sql
  pool: 5
  username: root
  password: "1988"
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/test.sql
  pool: 5
  username: root
  password: "1988"

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/production.sql
  pool: 5
  username: root
  password: "1988"

